/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesAirportTransfersRouteImport } from './routes/services.airport-transfers'
import { Route as ServicesGroupEventTransportRouteImport } from './routes/services.group-event-transport'
import { Route as ServicesLongDistanceTravelRouteImport } from './routes/services.long-distance-travel'
import { Route as ServicesPrivateCorporateTravelRouteImport } from './routes/services.private-corporate-travel'
import { Route as ToursIndexRouteImport } from './routes/tours.index'
import { Route as ToursSlugRouteImport } from './routes/tours.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAirportTransfersRoute =
  ServicesAirportTransfersRouteImport.update({
    id: '/services/airport-transfers',
    path: '/services/airport-transfers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesGroupEventTransportRoute =
  ServicesGroupEventTransportRouteImport.update({
    id: '/services/group-event-transport',
    path: '/services/group-event-transport',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesLongDistanceTravelRoute =
  ServicesLongDistanceTravelRouteImport.update({
    id: '/services/long-distance-travel',
    path: '/services/long-distance-travel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesPrivateCorporateTravelRoute =
  ServicesPrivateCorporateTravelRouteImport.update({
    id: '/services/private-corporate-travel',
    path: '/services/private-corporate-travel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/tours/',
  path: '/tours/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursSlugRoute = ToursSlugRouteImport.update({
  id: '/tours/$slug',
  path: '/tours/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/reviews': typeof ReviewsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/airport-transfers': typeof ServicesAirportTransfersRoute
  '/services/group-event-transport': typeof ServicesGroupEventTransportRoute
  '/services/long-distance-travel': typeof ServicesLongDistanceTravelRoute
  '/services/private-corporate-travel': typeof ServicesPrivateCorporateTravelRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tours/': typeof ToursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/reviews': typeof ReviewsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/airport-transfers': typeof ServicesAirportTransfersRoute
  '/services/group-event-transport': typeof ServicesGroupEventTransportRoute
  '/services/long-distance-travel': typeof ServicesLongDistanceTravelRoute
  '/services/private-corporate-travel': typeof ServicesPrivateCorporateTravelRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
  '/tours': typeof ToursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/reviews': typeof ReviewsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/airport-transfers': typeof ServicesAirportTransfersRoute
  '/services/group-event-transport': typeof ServicesGroupEventTransportRoute
  '/services/long-distance-travel': typeof ServicesLongDistanceTravelRoute
  '/services/private-corporate-travel': typeof ServicesPrivateCorporateTravelRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tours/': typeof ToursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/gallery'
    | '/reviews'
    | '/blog/$slug'
    | '/services/airport-transfers'
    | '/services/group-event-transport'
    | '/services/long-distance-travel'
    | '/services/private-corporate-travel'
    | '/tours/$slug'
    | '/blog/'
    | '/services/'
    | '/tours/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/gallery'
    | '/reviews'
    | '/blog/$slug'
    | '/services/airport-transfers'
    | '/services/group-event-transport'
    | '/services/long-distance-travel'
    | '/services/private-corporate-travel'
    | '/tours/$slug'
    | '/blog'
    | '/services'
    | '/tours'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/gallery'
    | '/reviews'
    | '/blog/$slug'
    | '/services/airport-transfers'
    | '/services/group-event-transport'
    | '/services/long-distance-travel'
    | '/services/private-corporate-travel'
    | '/tours/$slug'
    | '/blog/'
    | '/services/'
    | '/tours/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  ReviewsRoute: typeof ReviewsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ServicesAirportTransfersRoute: typeof ServicesAirportTransfersRoute
  ServicesGroupEventTransportRoute: typeof ServicesGroupEventTransportRoute
  ServicesLongDistanceTravelRoute: typeof ServicesLongDistanceTravelRoute
  ServicesPrivateCorporateTravelRoute: typeof ServicesPrivateCorporateTravelRoute
  ToursSlugRoute: typeof ToursSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ToursIndexRoute: typeof ToursIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/airport-transfers': {
      id: '/services/airport-transfers'
      path: '/services/airport-transfers'
      fullPath: '/services/airport-transfers'
      preLoaderRoute: typeof ServicesAirportTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/group-event-transport': {
      id: '/services/group-event-transport'
      path: '/services/group-event-transport'
      fullPath: '/services/group-event-transport'
      preLoaderRoute: typeof ServicesGroupEventTransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/long-distance-travel': {
      id: '/services/long-distance-travel'
      path: '/services/long-distance-travel'
      fullPath: '/services/long-distance-travel'
      preLoaderRoute: typeof ServicesLongDistanceTravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/private-corporate-travel': {
      id: '/services/private-corporate-travel'
      path: '/services/private-corporate-travel'
      fullPath: '/services/private-corporate-travel'
      preLoaderRoute: typeof ServicesPrivateCorporateTravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/': {
      id: '/tours/'
      path: '/tours'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$slug': {
      id: '/tours/$slug'
      path: '/tours/$slug'
      fullPath: '/tours/$slug'
      preLoaderRoute: typeof ToursSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  ReviewsRoute: ReviewsRoute,
  BlogSlugRoute: BlogSlugRoute,
  ServicesAirportTransfersRoute: ServicesAirportTransfersRoute,
  ServicesGroupEventTransportRoute: ServicesGroupEventTransportRoute,
  ServicesLongDistanceTravelRoute: ServicesLongDistanceTravelRoute,
  ServicesPrivateCorporateTravelRoute: ServicesPrivateCorporateTravelRoute,
  ToursSlugRoute: ToursSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ToursIndexRoute: ToursIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
